# Generated by Django 2.2.16 on 2020-10-25 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamMarkers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_seconds_start', models.IntegerField(default=0)),
                ('position_seconds_end', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255)),
                ('expiration', models.DateTimeField()),
                ('user_id', models.CharField(blank=True, max_length=50)),
                ('user_stream', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('N', 'New'), ('S', 'Started'), ('AD', 'Athlete Done'), ('RD', 'Review Done'), ('F', 'Finished'), ('D', 'Deleted')], default='N', max_length=2)),
                ('e1_done', models.BooleanField(default=False)),
                ('e2_done', models.BooleanField(default=False)),
                ('e3_done', models.BooleanField(default=False)),
                ('e4_done', models.BooleanField(default=False)),
                ('e1_include', models.BooleanField(default=True)),
                ('e2_include', models.BooleanField(default=True)),
                ('e3_include', models.BooleanField(default=True)),
                ('e4_include', models.BooleanField(default=True)),
                ('e1_name', models.CharField(blank=True, max_length=50)),
                ('e2_name', models.CharField(blank=True, max_length=50)),
                ('e3_name', models.CharField(blank=True, max_length=50)),
                ('e4_name', models.CharField(blank=True, max_length=50)),
                ('d1_name', models.CharField(blank=True, max_length=50)),
                ('score_elements', models.IntegerField(default=0)),
                ('score_difficulty', models.FloatField(default=0)),
                ('score_groups', models.FloatField(default=0)),
                ('score_bonus', models.FloatField(default=0)),
                ('score_neutral', models.FloatField(default=0)),
                ('score_e1', models.FloatField(default=0)),
                ('score_e2', models.FloatField(default=0)),
                ('score_e3', models.FloatField(default=0)),
                ('score_e4', models.FloatField(default=0)),
                ('score_e', models.FloatField(default=0)),
                ('score_d', models.FloatField(default=0)),
                ('score_final', models.FloatField(default=0)),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('athlete_done_time', models.BigIntegerField(blank=True, null=True)),
                ('d1_done_time', models.BigIntegerField(blank=True, null=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Athlete')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
        migrations.CreateModel(
            name='EJuryDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.IntegerField()),
                ('deduction', models.IntegerField()),
                ('editor', models.CharField(default='E', max_length=2)),
                ('time_stamp', models.BigIntegerField(blank=True, null=True)),
                ('time_stamp_relative', models.IntegerField(default=0)),
                ('artistry_type', models.CharField(blank=True, default='', max_length=10)),
                ('action', models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='Add', max_length=6)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Routine')),
            ],
        ),
    ]
