# Generated by Django 2.2.16 on 2020-09-08 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=10)),
                ('d1', models.CharField(max_length=50)),
                ('d1_affil', models.CharField(max_length=10)),
                ('d2', models.CharField(max_length=50)),
                ('d2_affil', models.CharField(max_length=10)),
                ('e1', models.CharField(max_length=50)),
                ('e1_affil', models.CharField(max_length=10)),
                ('e2', models.CharField(max_length=50)),
                ('e2_affil', models.CharField(max_length=10)),
                ('e3', models.CharField(max_length=50)),
                ('e3_affil', models.CharField(max_length=10)),
                ('e4', models.CharField(max_length=50)),
                ('e4_affil', models.CharField(max_length=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competition')),
            ],
        ),
    ]
