# Generated by Django 2.2.16 on 2020-09-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200908_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='team',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='d1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='d1_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='judge',
            name='d2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='d2_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e1_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e2_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e3_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e4',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e4_affil',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
