# Generated by Django 2.2.16 on 2020-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200909_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField()),
            ],
        ),
    ]
