# Generated by Django 2.2.16 on 2020-11-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_routine_video_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='d_judge',
            field=models.CharField(default='D1', max_length=2),
        ),
    ]
