# Generated by Django 2.2.16 on 2020-12-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_routine_d_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='score_connection',
            field=models.FloatField(default=0),
        ),
    ]
