# Generated by Django 2.2.16 on 2020-09-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_twitch_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitch',
            name='user_stream',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
