# Generated by Django 2.2.16 on 2020-12-02 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_startlist_secondary_judging'),
        ('app', '0007_auto_20201201_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(null=True, upload_to='backup_videos/')),
                ('reviewed', models.BooleanField(default=True)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Event')),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
    ]
