# Generated by Django 2.2.16 on 2020-09-16 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_twitch_user_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('N', 'New'), ('S', 'Started'), ('AD', 'Athlete Done'), ('RD', 'Review Done'), ('F', 'Finished'), ('D', 'Deleted')], default='N', max_length=2)),
                ('e1_done', models.BooleanField(default=False)),
                ('e2_done', models.BooleanField(default=False)),
                ('e3_done', models.BooleanField(default=False)),
                ('e4_done', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('athlete_done_time', models.DateTimeField()),
                ('judging_done_time', models.DateTimeField()),
                ('stream', models.CharField(max_length=255)),
                ('stream_video_id', models.CharField(max_length=255)),
                ('athlete', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Athlete')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competition')),
            ],
        ),
    ]
