# Generated by Django 2.2.16 on 2020-09-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_routine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='judging_done_time',
        ),
        migrations.AddField(
            model_name='routine',
            name='d1_done_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='athlete_done_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='routine',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
