# Generated by Django 2.2.16 on 2020-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_backupvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupvideo',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
