# Generated by Django 2.2.16 on 2020-09-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200916_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='EJuryDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge', models.CharField(max_length=50)),
                ('deduction', models.DecimalField(decimal_places=3, max_digits=5)),
                ('action', models.CharField(choices=[('Add', 'Add'), ('Edit', 'Edit'), ('Delete', 'Delete')], default='Add', max_length=6)),
                ('editor', models.CharField(default='E', max_length=2)),
                ('time_stamp', models.BigIntegerField(blank=True,null=True)),
                ('time_stamp_relative', models.IntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Routine')),
            ],
        ),
    ]
