# Generated by Django 2.2.16 on 2020-09-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_ejurydeduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='stream_video_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
