# Generated by Django 2.2.16 on 2020-12-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_routine_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='video_from_backup',
            field=models.BooleanField(default=False),
        ),
    ]
