# Generated by Django 2.2.16 on 2020-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20200918_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejurydeduction',
            name='deduction',
            field=models.IntegerField(),
        ),
    ]
