# Generated by Django 2.2.16 on 2020-12-04 22:01

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_routine_video_from_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupvideo',
            name='video_file',
            field=models.FileField(null=True, upload_to=app.models.backup_video_path),
        ),
    ]
