# Generated by Django 2.2.16 on 2020-12-05 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_startlist_secondary_judging'),
        ('app', '0014_auto_20201204_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='event_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Event'),
        ),
    ]
