# Generated by Django 2.2.16 on 2020-09-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200918_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='d1_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='e1_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='e2_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='e3_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='routine',
            name='e4_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='ejurydeduction',
            name='judge',
            field=models.IntegerField(),
        ),
    ]
