# Generated by Django 2.2.16 on 2020-09-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200919_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejurydeduction',
            name='artistry_type',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
