# Generated by Django 2.2.16 on 2020-09-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_ejurydeduction_artistry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='score_bonus',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_difficulty',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_elements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_groups',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_neutral',
            field=models.FloatField(default=0),
        ),
    ]
