# Generated by Django 2.2.16 on 2020-12-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_routine_eventfake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='event',
        ),
    ]
