# Generated by Django 2.2.16 on 2020-09-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20200921_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='score_d',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_e',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_e1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_e2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_e3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='routine',
            name='score_e4',
            field=models.FloatField(default=0),
        ),
    ]
