# Generated by Django 2.2.16 on 2020-12-05 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_routine_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='routine',
            old_name='event_link',
            new_name='event',
        ),
    ]
