# Generated by Django 2.2.16 on 2020-09-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200921_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='score_final',
            field=models.FloatField(default=0),
        ),
    ]
