# Generated by Django 2.2.16 on 2020-12-16 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20201204_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJuryFalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_judge', models.CharField(default='D1', max_length=2)),
                ('credit', models.BooleanField(default=False)),
                ('fall', models.BooleanField(default=False)),
                ('time_stamp', models.BigIntegerField(blank=True, null=True)),
                ('time_stamp_relative', models.IntegerField(default=0)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Routine')),
            ],
        ),
    ]
