# Generated by Django 2.2.16 on 2020-12-16 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_djuryfalls'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DJuryFalls',
            new_name='DJuryFall',
        ),
    ]
