# Generated by Django 2.2.16 on 2020-10-10 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_routine_score_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routine',
            name='stream_end_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='stream_start_time',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='stream_video_id',
        ),
    ]
