# Generated by Django 2.2.16 on 2020-12-16 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20201216_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djuryfall',
            name='d_judge',
        ),
    ]
