# Generated by Django 2.2.16 on 2020-12-16 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_djuryfall_d_judge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='djuryfall',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='djuryfall',
            name='time_stamp',
        ),
    ]
