# Generated by Django 2.2.16 on 2020-10-19 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_session_competition'),
        ('app', '0021_auto_20201017_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='judge',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='competition',
        ),
        migrations.AddField(
            model_name='routine',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Session'),
        ),
        migrations.DeleteModel(
            name='Athlete',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
