# Generated by Django 2.2.16 on 2020-12-16 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20201216_1433'),
    ]

    operations = [
        migrations.CreateModel(
            name='DJuryIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=False)),
                ('time_stamp_relative', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Fall', 'Fall'), ('Credit', 'Credit')], default='Fall', max_length=6)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Routine')),
            ],
        ),
        migrations.DeleteModel(
            name='DJuryFall',
        ),
    ]
