# Generated by Django 2.2.16 on 2020-10-19 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_session_competition'),
        ('app', '0022_auto_20201019_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='athlete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Athlete'),
        ),
    ]
