# Generated by Django 2.2.16 on 2020-12-31 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20201216_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
