# Generated by Django 2.2.16 on 2021-01-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20201230_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='score_final_d2',
            field=models.FloatField(default=0),
        ),
    ]
