# Generated by Django 2.2.16 on 2021-01-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_routine_score_final_d2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('do_conversions', models.BooleanField(default=True)),
            ],
        ),
    ]
