# Generated by Django 2.2.16 on 2021-01-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_conversionsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionsetting',
            name='e_dots_preview',
            field=models.BooleanField(default=True),
        ),
    ]
