# Generated by Django 2.2.16 on 2021-01-20 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_conversionsetting_e_dots_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('S', 'Started'), ('AD', 'Athlete Done'), ('RD', 'Review Done'), ('F', 'Finished'), ('D', 'Deleted'), ('M', 'Manual'), ('LV', 'LowerVault')], default='N', max_length=2),
        ),
    ]
