# Generated by Django 2.2.16 on 2021-03-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20210120_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversionsetting',
            name='endpoint_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
