# Generated by Django 2.2.16 on 2021-03-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_conversionsetting_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupvideo',
            name='job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
