# Generated by Django 2.2.16 on 2021-03-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_backupvideo_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='job_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
