# Generated by Django 2.2.16 on 2020-10-25 23:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WowzaStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(default='MAG', max_length=10)),
                ('event', models.CharField(default='FX', max_length=10)),
                ('stream_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('sdp_url', models.CharField(max_length=255)),
                ('application_name', models.CharField(max_length=20)),
                ('stream_name', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('started', 'started'), ('starting', 'starting'), ('stopped', 'stopped'), ('live', 'live')], default='stopped', max_length=10)),
                ('connected', models.BooleanField(default=False)),
                ('last_connected', models.DateTimeField(default=datetime.datetime.now)),
                ('session', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
    ]
