# Generated by Django 2.2.16 on 2020-10-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WowzaStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('sdp_url', models.CharField(max_length=255)),
                ('application_name', models.CharField(max_length=20)),
                ('stream_name', models.CharField(max_length=20)),
            ],
        ),
    ]
