# Generated by Django 2.2.16 on 2020-10-07 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_routine_score_final'),
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowzastream',
            name='competition',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Competition'),
        ),
        migrations.AddField(
            model_name='wowzastream',
            name='disc',
            field=models.CharField(default='MAG', max_length=10),
        ),
        migrations.AddField(
            model_name='wowzastream',
            name='event',
            field=models.CharField(default='FX', max_length=10),
        ),
    ]
