# Generated by Django 2.2.16 on 2020-10-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20201007_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowzastream',
            name='status',
            field=models.CharField(choices=[('Started', 'Started'), ('Stopped', 'Stopped'), ('Live', 'Live')], default='Stopped', max_length=10),
        ),
    ]
