# Generated by Django 2.2.16 on 2020-10-27 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_auto_20201027_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowzastream',
            name='hls_playback_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
