# Generated by Django 2.2.16 on 2020-10-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_wowzastream_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowzastream',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('starting', 'starting'), ('stopped', 'stopped'), ('live', 'live')], default='stopped', max_length=10),
        ),
    ]
