# Generated by Django 2.2.16 on 2020-10-30 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_wowzastream_hls_playback_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowzastream',
            name='wowza_player_code',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
