# Generated by Django 2.2.16 on 2020-10-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_auto_20201010_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowzastream',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
