# Generated by Django 2.2.16 on 2020-10-19 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_session_competition'),
        ('streaming', '0005_wowzastream_connected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wowzastream',
            name='competition',
        ),
        migrations.AddField(
            model_name='wowzastream',
            name='session',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Session'),
        ),
    ]
