# Generated by Django 2.2.16 on 2020-12-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
