# Generated by Django 2.2.16 on 2020-12-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_purchase_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('PANEL', 'Panel'), ('SPECTATE', 'Spectate'), ('ACCESS_CODE', 'Access Code'), ('SCOREBOARD', 'Scoreboard')], default='PANEL', max_length=2),
        ),
    ]
