# Generated by Django 2.2.16 on 2020-12-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20201224_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_connect_account',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
