# Generated by Django 2.2.16 on 2020-12-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20201224_1429'),
        ('account', '0006_user_stripe_connect_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sessions_available',
            field=models.ManyToManyField(blank=True, to='management.Session'),
        ),
    ]
