# Generated by Django 2.2.16 on 2020-12-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_user_sessions_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='type',
            field=models.CharField(choices=[('PANEL', 'Panel'), ('SPECTATE', 'Spectate'), ('ACCESS_CODE', 'Access Code'), ('SCOREBOARD', 'Scoreboard'), ('SPECTATE_CODE', 'Spectate Via Code')], default='PANEL', max_length=15),
        ),
    ]
