# Generated by Django 2.2.16 on 2020-12-31 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20201229_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='our_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
