# Generated by Django 2.2.16 on 2020-10-25 23:24

from django.db import migrations, models
import django.db.models.deletion
import management.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('type', models.CharField(choices=[('T', 'Tournament'), ('D', 'Dual'), ('I', 'Intrasquad')], default='T', max_length=2)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('disc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Disc')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('time', models.TimeField()),
                ('spectator_fee', models.DecimalField(decimal_places=2, default=2, max_digits=6)),
                ('competition', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Competition')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=management.models.sponsor_path)),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d1', models.CharField(blank=True, max_length=50)),
                ('d1_affil', models.CharField(blank=True, max_length=50)),
                ('d1_email', models.EmailField(blank=True, max_length=100)),
                ('d1_password', models.CharField(blank=True, max_length=50)),
                ('d2', models.CharField(blank=True, max_length=50)),
                ('d2_affil', models.CharField(blank=True, max_length=50)),
                ('d2_email', models.EmailField(blank=True, max_length=100)),
                ('d2_password', models.CharField(blank=True, max_length=50)),
                ('e1', models.CharField(blank=True, max_length=50)),
                ('e1_affil', models.CharField(blank=True, max_length=50)),
                ('e1_email', models.EmailField(blank=True, max_length=100)),
                ('e1_password', models.CharField(blank=True, max_length=50)),
                ('e2', models.CharField(blank=True, max_length=50)),
                ('e2_affil', models.CharField(blank=True, max_length=50)),
                ('e2_email', models.EmailField(blank=True, max_length=100)),
                ('e2_password', models.CharField(blank=True, max_length=50)),
                ('e3', models.CharField(blank=True, max_length=50)),
                ('e3_affil', models.CharField(blank=True, max_length=50)),
                ('e3_email', models.EmailField(blank=True, max_length=100)),
                ('e3_password', models.CharField(blank=True, max_length=50)),
                ('e4', models.CharField(blank=True, max_length=50)),
                ('e4_affil', models.CharField(blank=True, max_length=50)),
                ('e4_email', models.EmailField(blank=True, max_length=100)),
                ('e4_password', models.CharField(blank=True, max_length=50)),
                ('event', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='disc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Disc'),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('events', models.ManyToManyField(to='management.Event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
                ('teams', models.ManyToManyField(to='management.Team')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('abbreviation', models.CharField(blank=True, max_length=6)),
                ('disc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Disc')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=8)),
                ('rotation', models.CharField(default='A', max_length=2)),
                ('level', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.AthleteLevel')),
                ('team', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Team')),
            ],
        ),
    ]
