# Generated by Django 2.2.16 on 2020-10-19 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('disc', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('T', 'Tournament'), ('D', 'Dual'), ('I', 'Intrasquad')], default='T', max_length=2)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=10)),
                ('d1', models.CharField(blank=True, max_length=50)),
                ('d1_affil', models.CharField(blank=True, max_length=10)),
                ('d2', models.CharField(blank=True, max_length=50)),
                ('d2_affil', models.CharField(blank=True, max_length=10)),
                ('e1', models.CharField(blank=True, max_length=50)),
                ('e1_affil', models.CharField(blank=True, max_length=10)),
                ('e2', models.CharField(blank=True, max_length=50)),
                ('e2_affil', models.CharField(blank=True, max_length=10)),
                ('e3', models.CharField(blank=True, max_length=50)),
                ('e3_affil', models.CharField(blank=True, max_length=10)),
                ('e4', models.CharField(blank=True, max_length=50)),
                ('e4_affil', models.CharField(blank=True, max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('team', models.CharField(blank=True, max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
    ]
