# Generated by Django 2.2.16 on 2020-10-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_competition_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='coach_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='head_coach_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='spectator_fee',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
