# Generated by Django 2.2.16 on 2020-10-20 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_session_competition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='status',
            new_name='type',
        ),
    ]
