# Generated by Django 2.2.16 on 2020-10-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20201020_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='d1_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='d1_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='d2_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='d2_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e1_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e1_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e2_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e2_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e3_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e3_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e4_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='judge',
            name='e4_password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
