# Generated by Django 2.2.16 on 2020-10-27 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_remove_wowzastream_session'),
        ('management', '0003_auto_20201026_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='stream',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='streaming.WowzaStream'),
        ),
    ]
