# Generated by Django 2.2.16 on 2020-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20201021_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='d1_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
    ]
