# Generated by Django 2.2.16 on 2020-10-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201022_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='d1_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='d2_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e1_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e2_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e3_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='judge',
            name='e4_email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
