# Generated by Django 2.2.16 on 2020-10-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20201022_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='session',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='team',
        ),
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='athlete',
            name='rotation',
            field=models.CharField(default='A', max_length=2),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('abbreviation', models.CharField(blank=True, max_length=4)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
            ],
        ),
    ]
