# Generated by Django 2.2.16 on 2020-10-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201022_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Team'),
        ),
    ]
