# Generated by Django 2.2.16 on 2020-11-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_athletelevel_scoring_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='competition',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
