# Generated by Django 2.2.16 on 2020-10-22 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201022_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='level',
        ),
    ]
