# Generated by Django 2.2.16 on 2020-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201122_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='events_competing',
            field=models.ManyToManyField(blank=True, related_name='events_competing_related', to='management.Event'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='events_count_for_team',
            field=models.ManyToManyField(blank=True, to='management.Event'),
        ),
    ]
