# Generated by Django 2.2.16 on 2020-10-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201022_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.AthleteLevel'),
        ),
    ]
