# Generated by Django 2.2.16 on 2020-11-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20201122_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='test',
        ),
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
