# Generated by Django 2.2.16 on 2020-11-28 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20201126_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='startlist',
            name='secondary_judging',
            field=models.BooleanField(default=False),
        ),
    ]
