# Generated by Django 2.2.16 on 2020-10-23 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_auto_20201023_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Event'),
        ),
    ]
