# Generated by Django 2.2.16 on 2020-12-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_rotationorder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rotationorder',
            options={'ordering': ['rotation', 'order']},
        ),
        migrations.AlterField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(max_length=4),
        ),
    ]
