# Generated by Django 2.2.16 on 2020-10-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20201023_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athletelevel',
            name='disc',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='disc',
        ),
    ]
