# Generated by Django 2.2.16 on 2020-12-12 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_auto_20201208_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='top_counting_for_score',
            field=models.IntegerField(default=5),
        ),
    ]
