# Generated by Django 2.2.16 on 2020-10-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20201023_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletelevel',
            name='disc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Disc'),
        ),
        migrations.AddField(
            model_name='competition',
            name='disc',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.Disc'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='level',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.AthleteLevel'),
        ),
    ]
