# Generated by Django 2.2.16 on 2020-12-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_session_top_counting_for_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='current_event',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cam_current_event', to='management.Event'),
        ),
    ]
