# Generated by Django 2.2.16 on 2020-10-23 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_auto_20201023_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=50)),
                ('events', models.ManyToManyField(to='management.Event')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Session')),
                ('teams', models.ManyToManyField(to='management.Team')),
            ],
        ),
    ]
