# Generated by Django 2.2.16 on 2020-12-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0019_session_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
