# Generated by Django 2.2.16 on 2020-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_auto_20201023_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='spectator_fee',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=6),
        ),
    ]
