# Generated by Django 2.2.16 on 2020-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0022_session_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='payment_intent',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
