# Generated by Django 2.2.16 on 2020-12-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0023_session_payment_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='access_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='access_code_total',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='session',
            name='access_code_used',
            field=models.IntegerField(default=0),
        ),
    ]
