# Generated by Django 2.2.16 on 2020-12-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0024_auto_20201224_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
