# Generated by Django 2.2.16 on 2021-01-04 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0025_session_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='use_ejudge_dots',
            field=models.BooleanField(default=True),
        ),
    ]
