# Generated by Django 2.2.16 on 2021-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0027_auto_20210106_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='level',
            field=models.CharField(choices=[('NCAA', 'NCAA'), ('FIG', 'FIG'), ('USAG', 'USAG'), ('WDP', 'WDP'), ('MDP', 'MDP')], default='NCAA', max_length=6),
        ),
    ]
