# Generated by Django 2.2.16 on 2021-01-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0028_auto_20210108_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('order', models.IntegerField(default=1)),
                ('athlete_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.AthleteLevel')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
