# Generated by Django 2.2.16 on 2021-01-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0029_athleteage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='age',
        ),
    ]
