# Generated by Django 2.2.16 on 2021-01-08 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0030_remove_athlete_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='age',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.AthleteAge'),
        ),
    ]
