# Generated by Django 2.2.16 on 2021-01-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0031_athlete_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteage',
            name='athlete_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_age', to='management.AthleteLevel'),
        ),
    ]
