# Generated by Django 2.2.16 on 2021-01-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0032_auto_20210108_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='admin_test_mode',
            field=models.BooleanField(default=False),
        ),
    ]
