# Generated by Django 2.2.16 on 2021-01-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0033_session_admin_test_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='admin_test_mode',
            field=models.BooleanField(default=True),
        ),
    ]
