# Generated by Django 2.2.16 on 2021-02-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0035_auto_20210126_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='video_opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
